## Append samples of your project ##
resources:
- ha_v1_homeassistant.yaml
- ha_v1_homeassistantsecrets.yaml
- ha_v1_homeassistant_with_bootstrap.yaml
- ha_v1_homeassistant_with_config.yaml
- haconfig_hot_reload_strategy.yaml
- haconfig_restart_strategy.yaml
- complete_example_with_secrets.yaml
- ha_v1_gateway_api.yaml
- ha_v1_ingress_tls.yaml
- ha_v1_gateway_managed_tls.yaml
- ha_v1_homeassistantintegration_mqtt.yaml
- ha_v1_homeassistantintegration_recorder.yaml
- ha_v1_homeassistantfloor.yaml
- ha_v1_homeassistantlabel.yaml
- ha_v1_homeassistantarea.yaml
- ha_v1_homeassistantcommunityrepository.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
