//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationAction) DeepCopyInto(out *AutomationAction) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationAction.
func (in *AutomationAction) DeepCopy() *AutomationAction {
	if in == nil {
		return nil
	}
	out := new(AutomationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationCondition) DeepCopyInto(out *AutomationCondition) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationCondition.
func (in *AutomationCondition) DeepCopy() *AutomationCondition {
	if in == nil {
		return nil
	}
	out := new(AutomationCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationTrigger) DeepCopyInto(out *AutomationTrigger) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationTrigger.
func (in *AutomationTrigger) DeepCopy() *AutomationTrigger {
	if in == nil {
		return nil
	}
	out := new(AutomationTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSpec) DeepCopyInto(out *BackupSpec) {
	*out = *in
	if in.RetentionCopies != nil {
		in, out := &in.RetentionCopies, &out.RetentionCopies
		*out = new(int32)
		**out = **in
	}
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.IncludeDatabase != nil {
		in, out := &in.IncludeDatabase, &out.IncludeDatabase
		*out = new(bool)
		**out = **in
	}
	if in.AgentIDs != nil {
		in, out := &in.AgentIDs, &out.AgentIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSpec.
func (in *BackupSpec) DeepCopy() *BackupSpec {
	if in == nil {
		return nil
	}
	out := new(BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapCredentials) DeepCopyInto(out *BootstrapCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(CredentialsSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapCredentials.
func (in *BootstrapCredentials) DeepCopy() *BootstrapCredentials {
	if in == nil {
		return nil
	}
	out := new(BootstrapCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(BootstrapCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(LocationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatus) DeepCopyInto(out *BootstrapStatus) {
	*out = *in
	if in.LastAttempt != nil {
		in, out := &in.LastAttempt, &out.LastAttempt
		*out = (*in).DeepCopy()
	}
	if in.OnboardingDoneFirstSeen != nil {
		in, out := &in.OnboardingDoneFirstSeen, &out.OnboardingDoneFirstSeen
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatus.
func (in *BootstrapStatus) DeepCopy() *BootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConfig) DeepCopyInto(out *HTTPConfig) {
	*out = *in
	if in.CORSDomains != nil {
		in, out := &in.CORSDomains, &out.CORSDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TrustProxy != nil {
		in, out := &in.TrustProxy, &out.TrustProxy
		*out = new(bool)
		**out = **in
	}
	if in.UseXForwardedFor != nil {
		in, out := &in.UseXForwardedFor, &out.UseXForwardedFor
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConfig.
func (in *HTTPConfig) DeepCopy() *HTTPConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistant) DeepCopyInto(out *HomeAssistant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistant.
func (in *HomeAssistant) DeepCopy() *HomeAssistant {
	if in == nil {
		return nil
	}
	out := new(HomeAssistant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantArea) DeepCopyInto(out *HomeAssistantArea) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantArea.
func (in *HomeAssistantArea) DeepCopy() *HomeAssistantArea {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantArea)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantArea) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAreaList) DeepCopyInto(out *HomeAssistantAreaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantArea, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAreaList.
func (in *HomeAssistantAreaList) DeepCopy() *HomeAssistantAreaList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAreaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantAreaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAreaSpec) DeepCopyInto(out *HomeAssistantAreaSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAreaSpec.
func (in *HomeAssistantAreaSpec) DeepCopy() *HomeAssistantAreaSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAreaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAreaStatus) DeepCopyInto(out *HomeAssistantAreaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAreaStatus.
func (in *HomeAssistantAreaStatus) DeepCopy() *HomeAssistantAreaStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAreaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAutomation) DeepCopyInto(out *HomeAssistantAutomation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAutomation.
func (in *HomeAssistantAutomation) DeepCopy() *HomeAssistantAutomation {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAutomation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantAutomation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAutomationList) DeepCopyInto(out *HomeAssistantAutomationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantAutomation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAutomationList.
func (in *HomeAssistantAutomationList) DeepCopy() *HomeAssistantAutomationList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAutomationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantAutomationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAutomationSpec) DeepCopyInto(out *HomeAssistantAutomationSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]AutomationTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AutomationCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]AutomationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	if in.InitialState != nil {
		in, out := &in.InitialState, &out.InitialState
		*out = new(bool)
		**out = **in
	}
	if in.AutoReload != nil {
		in, out := &in.AutoReload, &out.AutoReload
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAutomationSpec.
func (in *HomeAssistantAutomationSpec) DeepCopy() *HomeAssistantAutomationSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAutomationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantAutomationStatus) DeepCopyInto(out *HomeAssistantAutomationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReloadTime != nil {
		in, out := &in.LastReloadTime, &out.LastReloadTime
		*out = (*in).DeepCopy()
	}
	if in.LastTriggeredTime != nil {
		in, out := &in.LastTriggeredTime, &out.LastTriggeredTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantAutomationStatus.
func (in *HomeAssistantAutomationStatus) DeepCopy() *HomeAssistantAutomationStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantAutomationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantConfiguration) DeepCopyInto(out *HomeAssistantConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantConfiguration.
func (in *HomeAssistantConfiguration) DeepCopy() *HomeAssistantConfiguration {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantConfigurationList) DeepCopyInto(out *HomeAssistantConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantConfigurationList.
func (in *HomeAssistantConfigurationList) DeepCopy() *HomeAssistantConfigurationList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantConfigurationSpec) DeepCopyInto(out *HomeAssistantConfigurationSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.AutoReload != nil {
		in, out := &in.AutoReload, &out.AutoReload
		*out = new(bool)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logger != nil {
		in, out := &in.Logger, &out.Logger
		*out = new(LoggerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Recorder != nil {
		in, out := &in.Recorder, &out.Recorder
		*out = new(RecorderConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MQTT != nil {
		in, out := &in.MQTT, &out.MQTT
		*out = new(MQTTConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantConfigurationSpec.
func (in *HomeAssistantConfigurationSpec) DeepCopy() *HomeAssistantConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantConfigurationStatus) DeepCopyInto(out *HomeAssistantConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReloadTime != nil {
		in, out := &in.LastReloadTime, &out.LastReloadTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantConfigurationStatus.
func (in *HomeAssistantConfigurationStatus) DeepCopy() *HomeAssistantConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantFloor) DeepCopyInto(out *HomeAssistantFloor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantFloor.
func (in *HomeAssistantFloor) DeepCopy() *HomeAssistantFloor {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantFloor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantFloor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantFloorList) DeepCopyInto(out *HomeAssistantFloorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantFloor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantFloorList.
func (in *HomeAssistantFloorList) DeepCopy() *HomeAssistantFloorList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantFloorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantFloorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantFloorSpec) DeepCopyInto(out *HomeAssistantFloorSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantFloorSpec.
func (in *HomeAssistantFloorSpec) DeepCopy() *HomeAssistantFloorSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantFloorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantFloorStatus) DeepCopyInto(out *HomeAssistantFloorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantFloorStatus.
func (in *HomeAssistantFloorStatus) DeepCopy() *HomeAssistantFloorStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantFloorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantIntegration) DeepCopyInto(out *HomeAssistantIntegration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantIntegration.
func (in *HomeAssistantIntegration) DeepCopy() *HomeAssistantIntegration {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantIntegration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantIntegrationList) DeepCopyInto(out *HomeAssistantIntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantIntegrationList.
func (in *HomeAssistantIntegrationList) DeepCopy() *HomeAssistantIntegrationList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantIntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantIntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantIntegrationSpec) DeepCopyInto(out *HomeAssistantIntegrationSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make(map[string]IntegrationValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantIntegrationSpec.
func (in *HomeAssistantIntegrationSpec) DeepCopy() *HomeAssistantIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantIntegrationStatus) DeepCopyInto(out *HomeAssistantIntegrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantIntegrationStatus.
func (in *HomeAssistantIntegrationStatus) DeepCopy() *HomeAssistantIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantLabel) DeepCopyInto(out *HomeAssistantLabel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantLabel.
func (in *HomeAssistantLabel) DeepCopy() *HomeAssistantLabel {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantLabel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantLabelList) DeepCopyInto(out *HomeAssistantLabelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantLabel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantLabelList.
func (in *HomeAssistantLabelList) DeepCopy() *HomeAssistantLabelList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantLabelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantLabelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantLabelSpec) DeepCopyInto(out *HomeAssistantLabelSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantLabelSpec.
func (in *HomeAssistantLabelSpec) DeepCopy() *HomeAssistantLabelSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantLabelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantLabelStatus) DeepCopyInto(out *HomeAssistantLabelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantLabelStatus.
func (in *HomeAssistantLabelStatus) DeepCopy() *HomeAssistantLabelStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantLabelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantList) DeepCopyInto(out *HomeAssistantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantList.
func (in *HomeAssistantList) DeepCopy() *HomeAssistantList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantReference) DeepCopyInto(out *HomeAssistantReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantReference.
func (in *HomeAssistantReference) DeepCopy() *HomeAssistantReference {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantScene) DeepCopyInto(out *HomeAssistantScene) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantScene.
func (in *HomeAssistantScene) DeepCopy() *HomeAssistantScene {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantScene)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantScene) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSceneList) DeepCopyInto(out *HomeAssistantSceneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantScene, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSceneList.
func (in *HomeAssistantSceneList) DeepCopy() *HomeAssistantSceneList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSceneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantSceneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSceneSpec) DeepCopyInto(out *HomeAssistantSceneSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Entities != nil {
		in, out := &in.Entities, &out.Entities
		*out = make([]SceneEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoReload != nil {
		in, out := &in.AutoReload, &out.AutoReload
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSceneSpec.
func (in *HomeAssistantSceneSpec) DeepCopy() *HomeAssistantSceneSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSceneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSceneStatus) DeepCopyInto(out *HomeAssistantSceneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReloadTime != nil {
		in, out := &in.LastReloadTime, &out.LastReloadTime
		*out = (*in).DeepCopy()
	}
	if in.LastActivated != nil {
		in, out := &in.LastActivated, &out.LastActivated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSceneStatus.
func (in *HomeAssistantSceneStatus) DeepCopy() *HomeAssistantSceneStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSceneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantScript) DeepCopyInto(out *HomeAssistantScript) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantScript.
func (in *HomeAssistantScript) DeepCopy() *HomeAssistantScript {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantScript) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantScriptList) DeepCopyInto(out *HomeAssistantScriptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantScriptList.
func (in *HomeAssistantScriptList) DeepCopy() *HomeAssistantScriptList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantScriptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantScriptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantScriptSpec) DeepCopyInto(out *HomeAssistantScriptSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.Sequence != nil {
		in, out := &in.Sequence, &out.Sequence
		*out = make([]ScriptAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]ScriptField, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	if in.AutoReload != nil {
		in, out := &in.AutoReload, &out.AutoReload
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantScriptSpec.
func (in *HomeAssistantScriptSpec) DeepCopy() *HomeAssistantScriptSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantScriptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantScriptStatus) DeepCopyInto(out *HomeAssistantScriptStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReloadTime != nil {
		in, out := &in.LastReloadTime, &out.LastReloadTime
		*out = (*in).DeepCopy()
	}
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantScriptStatus.
func (in *HomeAssistantScriptStatus) DeepCopy() *HomeAssistantScriptStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantScriptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSecrets) DeepCopyInto(out *HomeAssistantSecrets) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSecrets.
func (in *HomeAssistantSecrets) DeepCopy() *HomeAssistantSecrets {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantSecrets) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSecretsList) DeepCopyInto(out *HomeAssistantSecretsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantSecrets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSecretsList.
func (in *HomeAssistantSecretsList) DeepCopy() *HomeAssistantSecretsList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSecretsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantSecretsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSecretsSpec) DeepCopyInto(out *HomeAssistantSecretsSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make([]SecretKeyReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoRestart != nil {
		in, out := &in.AutoRestart, &out.AutoRestart
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSecretsSpec.
func (in *HomeAssistantSecretsSpec) DeepCopy() *HomeAssistantSecretsSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSecretsStatus) DeepCopyInto(out *HomeAssistantSecretsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSecretsStatus.
func (in *HomeAssistantSecretsStatus) DeepCopy() *HomeAssistantSecretsStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSecretsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantSpec) DeepCopyInto(out *HomeAssistantSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceSpec)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretsFrom != nil {
		in, out := &in.SecretsFrom, &out.SecretsFrom
		*out = new(SecretReference)
		**out = **in
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(BootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantSpec.
func (in *HomeAssistantSpec) DeepCopy() *HomeAssistantSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantStatus) DeepCopyInto(out *HomeAssistantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(BootstrapStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSelfUnban != nil {
		in, out := &in.LastSelfUnban, &out.LastSelfUnban
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantStatus.
func (in *HomeAssistantStatus) DeepCopy() *HomeAssistantStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(IngressTLSSpec)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSSpec) DeepCopyInto(out *IngressTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSSpec.
func (in *IngressTLSSpec) DeepCopy() *IngressTLSSpec {
	if in == nil {
		return nil
	}
	out := new(IngressTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitContainerSpec) DeepCopyInto(out *InitContainerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitContainerSpec.
func (in *InitContainerSpec) DeepCopy() *InitContainerSpec {
	if in == nil {
		return nil
	}
	out := new(InitContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSecretKeyRef) DeepCopyInto(out *IntegrationSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSecretKeyRef.
func (in *IntegrationSecretKeyRef) DeepCopy() *IntegrationSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(IntegrationSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationValue) DeepCopyInto(out *IntegrationValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.JSONValue != nil {
		in, out := &in.JSONValue, &out.JSONValue
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(IntegrationSecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationValue.
func (in *IntegrationValue) DeepCopy() *IntegrationValue {
	if in == nil {
		return nil
	}
	out := new(IntegrationValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationConfig) DeepCopyInto(out *LocationConfig) {
	*out = *in
	if in.Elevation != nil {
		in, out := &in.Elevation, &out.Elevation
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationConfig.
func (in *LocationConfig) DeepCopy() *LocationConfig {
	if in == nil {
		return nil
	}
	out := new(LocationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggerConfig) DeepCopyInto(out *LoggerConfig) {
	*out = *in
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggerConfig.
func (in *LoggerConfig) DeepCopy() *LoggerConfig {
	if in == nil {
		return nil
	}
	out := new(LoggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTConfig) DeepCopyInto(out *MQTTConfig) {
	*out = *in
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTConfig.
func (in *MQTTConfig) DeepCopy() *MQTTConfig {
	if in == nil {
		return nil
	}
	out := new(MQTTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecorderConfig) DeepCopyInto(out *RecorderConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseSecretRef != nil {
		in, out := &in.DatabaseSecretRef, &out.DatabaseSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.PurgeKeepDays != nil {
		in, out := &in.PurgeKeepDays, &out.PurgeKeepDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecorderConfig.
func (in *RecorderConfig) DeepCopy() *RecorderConfig {
	if in == nil {
		return nil
	}
	out := new(RecorderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SceneEntity) DeepCopyInto(out *SceneEntity) {
	*out = *in
	in.Attributes.DeepCopyInto(&out.Attributes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SceneEntity.
func (in *SceneEntity) DeepCopy() *SceneEntity {
	if in == nil {
		return nil
	}
	out := new(SceneEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptAction) DeepCopyInto(out *ScriptAction) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptAction.
func (in *ScriptAction) DeepCopy() *ScriptAction {
	if in == nil {
		return nil
	}
	out := new(ScriptAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptField) DeepCopyInto(out *ScriptField) {
	*out = *in
	in.RawExtension.DeepCopyInto(&out.RawExtension)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptField.
func (in *ScriptField) DeepCopy() *ScriptField {
	if in == nil {
		return nil
	}
	out := new(ScriptField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = new(InitContainerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
