//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyReference) DeepCopyInto(out *ConfigMapKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyReference.
func (in *ConfigMapKeyReference) DeepCopy() *ConfigMapKeyReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantCommunityRepository) DeepCopyInto(out *HomeAssistantCommunityRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantCommunityRepository.
func (in *HomeAssistantCommunityRepository) DeepCopy() *HomeAssistantCommunityRepository {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantCommunityRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantCommunityRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantCommunityRepositoryList) DeepCopyInto(out *HomeAssistantCommunityRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantCommunityRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantCommunityRepositoryList.
func (in *HomeAssistantCommunityRepositoryList) DeepCopy() *HomeAssistantCommunityRepositoryList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantCommunityRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantCommunityRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantCommunityRepositorySpec) DeepCopyInto(out *HomeAssistantCommunityRepositorySpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantCommunityRepositorySpec.
func (in *HomeAssistantCommunityRepositorySpec) DeepCopy() *HomeAssistantCommunityRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantCommunityRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantCommunityRepositoryStatus) DeepCopyInto(out *HomeAssistantCommunityRepositoryStatus) {
	*out = *in
	if in.InstallingSince != nil {
		in, out := &in.InstallingSince, &out.InstallingSince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantCommunityRepositoryStatus.
func (in *HomeAssistantCommunityRepositoryStatus) DeepCopy() *HomeAssistantCommunityRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantCommunityRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantDashboard) DeepCopyInto(out *HomeAssistantDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantDashboard.
func (in *HomeAssistantDashboard) DeepCopy() *HomeAssistantDashboard {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantDashboardList) DeepCopyInto(out *HomeAssistantDashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HomeAssistantDashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantDashboardList.
func (in *HomeAssistantDashboardList) DeepCopy() *HomeAssistantDashboardList {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantDashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HomeAssistantDashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantDashboardSpec) DeepCopyInto(out *HomeAssistantDashboardSpec) {
	*out = *in
	out.HomeAssistantRef = in.HomeAssistantRef
	if in.ShowInSidebar != nil {
		in, out := &in.ShowInSidebar, &out.ShowInSidebar
		*out = new(bool)
		**out = **in
	}
	if in.RequireAdmin != nil {
		in, out := &in.RequireAdmin, &out.RequireAdmin
		*out = new(bool)
		**out = **in
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantDashboardSpec.
func (in *HomeAssistantDashboardSpec) DeepCopy() *HomeAssistantDashboardSpec {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantDashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantDashboardStatus) DeepCopyInto(out *HomeAssistantDashboardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantDashboardStatus.
func (in *HomeAssistantDashboardStatus) DeepCopy() *HomeAssistantDashboardStatus {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantDashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HomeAssistantReference) DeepCopyInto(out *HomeAssistantReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HomeAssistantReference.
func (in *HomeAssistantReference) DeepCopy() *HomeAssistantReference {
	if in == nil {
		return nil
	}
	out := new(HomeAssistantReference)
	in.DeepCopyInto(out)
	return out
}
